# Install CRAN packages
install.packages("tidyverse")
install.packages("kableExtra")
install.packages("here")
install.packages("lubridate")
install.packages("stringr")
install.packages("scales")
install.packages("grid")
install.packages("gridBase")
install.packages("gridExtra")
install.packages("rjson")
